### PR TITLE
[feat] multistep_loop APIs

### PR DESCRIPTION
**Pull request by peterychang**
Added 2 new APIs for `report_outcome` that take in the event ID and the episode object. Discussed with Wangda

### CODE REVIEW

**Comment by peterychang** [comment]
I think the only remaining test that uses the old interface is rl_sim (used in the end-to-end tests)

**Comment by bassmang** [comment]
> I think the only remaining test that uses the old interface is rl_sim (used in the end-to-end tests)

Would it be possible to add a test to `live_model_test.cc` like the other loop tests? And add something small to `live_model_test_legacy.cc` with the old interface. Otherwise lgtm

**Review by rajan-chari — APPROVED** [review]
Look good to me.  Thanks Peter

**Comment by peterychang** [comment]
@bassmang Actually, I can't really add multistep into the normal testing framework because its only built into the clientlib when using the external_parser makefile. I'll merge this for now and look into expanding the external parser tests a bit more

**Pull request merged**
