### PR TITLE
Revert "mac ci: continue on error true (#327)"

### PR DESCRIPTION
**Pull request by lalo**
This reverts commit 763c4c78eb2ea5eecc6901638ac6431e83dbb07b.

Mac CI currently fails. Either we should fix or remove. This would turn back on the failing CI.

Related:
https://github.com/VowpalWabbit/reinforcement_learning/issues/300

Reverts
https://github.com/VowpalWabbit/reinforcement_learning/pull/327

### CODE REVIEW

**Comment by kumpera** [comment]
I just ran into the issue, do you mind if I just fix it instead?

**Comment by kumpera** [comment]
https://github.com/VowpalWabbit/reinforcement_learning/pull/386

**Comment by kumpera** [comment]
Closing as we have a PR to fix the build instead.

**Comment by lalo** [comment]
We technically still need to revert, to remove fail success in future breaks.

**Comment by kumpera** [comment]
> 
> 
> We technically still need to revert, to remove fail success in future breaks.

I don't follow you what you mean. What happens with future breakage?

**Comment by lalo** [comment]
If it breaks in the future again, the CI will pass bc it is set to "continueOnError: true". This reverts that, but this should be merged after your PR.

**Comment by kumpera** [comment]
@lalo I thought this PR was reverting the change the broke mac CI in the first place.

Why did we disable it to begin with?

Disabled CI lanes should be a temporary situation and treated as an urgent matter. They should be deleted otherwise.

**Comment by olgavrou** [comment]
@lalo @kumpera this seems to fix the mac ci: https://github.com/VowpalWabbit/reinforcement_learning/pull/390 so we can then merge this PR too

**Pull request merged**
