### PR TITLE
Enable ControlFlowGuard

### PR DESCRIPTION
**Pull request by tyclintw**
Necessary for the native dll to pass binskim.

### CODE REVIEW

**Comment by jackgerrits** [comment]
Could you please enable this in CMake aswell?

**Comment by rajan-chari** [comment]
Reviewed.  Looks good. No comments.

**Comment by lokitoth** [comment]
>           Could you please enable this in CMake aswell?

I think this is a compiler/linker specific feature. I believe it exists in Clang as Control Flow Integrity, but I do not know if GCC has it. There may be third-party libraries that can be used here: https://grsecurity.net/rap_faq.php

I have a question: Does this impact the return callback in the evening layer? I tried finding documentation on CFG and P/Invoke, but could not see any details.

**Comment by jackgerrits** [comment]
We can add compiler flags depending on the compiler being used. So we can check if it is MSVC or Clang etc and act accordingly

**Pull request merged**
